steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dagster-demo-slack', '-f', './Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dagster-demo-slack']
images:
  - 'gcr.io/$PROJECT_ID/dagster-demo-slack'
options:
  logging: CLOUD_LOGGING_ONLY